INSERT INTO ORGANIZATION (ID, NAME) VALUES (1, 'Mock Organisation');
INSERT INTO HELP_REQUEST (ID, TITLE, DESCRIPTION, LOCATION, REQUEST_DATE, ORGANIZATION_ID) VALUES (1, 'Mock Anfrage 1', 'Beschreibung Mock Anfrage 1', 'Ort 1', TO_DATE('dd.MM.yyyy', '21.03.2020'), 1);
INSERT INTO HELP_REQUEST (ID, TITLE, DESCRIPTION, LOCATION, REQUEST_DATE, ORGANIZATION_ID) VALUES (2, 'Mock Anfrage 2', 'Beschreibung Mock Anfrage 2', 'Ort 2', TO_DATE('dd.MM.yyyy', '21.03.2020'), 1);
